### ISSUE TITLE
API connection to Waze's database

### ISSUE THREAD

**Issue by canales** [EL-BID/Congestiometro-GCBA#2]
Hi @Argentan I was trying to find how this program was getting access to Waze's data but couldn't find any API nor any connection of this sort. Does this mean that this program should connect to a database which Waze has already given you access to and then load it in here via the ETL component?

thanks

**Comment by Argentan** [comment]
Hi @canales , the ETL is not standardizable since it must interact with the systems of each city. The congestiometer stablishes a standar data structure but the translation should be done by each city. The data can come from Waze or any other system the city has in place to track jams. Access to Waze api can be requested , as far as i know,  by public officials of each city

**Comment by canales** [comment]
Gracias Rafael. Ahora entiendo que es un software modular para medir congestionamiento a partir del feed de datos disponible de la ciudad. Aunque me imagino que las funcionalidades están construidas mayoritariamente en función de los datos que Waze proporciona. 

Yo no tengo acceso al API que Waze le proporciona a la ciudades, pero sabes si dentro de los datos que ellos proporcionan se encuentra la de los limites de velocidad permitidos? Esto no sería lo mismo que la velocidad promedio de los coches en circulación, que veo que es un indicador aquí recopilado, sino la velocidad máxima permitida por segmento de calle. Gracias

**Comment by Argentan** [comment]
Hola  @canales, creo que la  velocidad máxima no está dentro de los datos de Waze, sino que cada jurisdicción los tiene mapeados según sus propios criterios
